import * as functionTemplates from './function-templates'

import { DETAILED_FUNCTIONS } from './detailed'

/** @hidden */
export const BASIC_FUNCTIONS = {
  ...DETAILED_FUNCTIONS,
  "AbilityModificationArray": functionTemplates.removeFromOutput,
  "Behavior": functionTemplates.removeFromOutput,
  "BehaviorArray": functionTemplates.removeFromOutput,
  "CancelEffect": functionTemplates.removeFromOutput,
  "CaseDefault": functionTemplates.removeFromOutput,
  "CastOutroTimeEffect": functionTemplates.removeFromOutput,
  "CombineArray": functionTemplates.removeFromOutput,
  "CountEffect": functionTemplates.removeFromOutput,
  "CritValidatorArray": functionTemplates.removeFromOutput,
  "DeathUnloadEffect": functionTemplates.removeFromOutput,
  "DisplayEffect": functionTemplates.removeFromOutput,
  "Effect": functionTemplates.removeFromOutput,
  "EffectArray": functionTemplates.removeFromOutput,
  "EffectRange": functionTemplates.removeFromOutput,
  "Exhausted": functionTemplates.removeFromOutput,
  "ExpireEffect": functionTemplates.removeFromOutput,
  "FinalEffect": functionTemplates.removeFromOutput,
  "FollowRange": functionTemplates.removeFromOutput,
  "Handled": functionTemplates.removeFromOutput,
  "HitsChangedEffect": functionTemplates.removeFromOutput,
  "InitialEffect": functionTemplates.removeFromOutput,
  "ImpactEffect": functionTemplates.removeFromOutput,
  "LaunchEffect": functionTemplates.removeFromOutput,
  "LaunchMissileEffect": functionTemplates.removeFromOutput,
  "LevelScalingArray": functionTemplates.removeFromOutput,
  "LoadCargoEffect": functionTemplates.removeFromOutput,
  "MinVeterancyXP": functionTemplates.removeFromOutput,
  "PeriodicEffect": functionTemplates.removeFromOutput,
  "PeriodicEffectArray": functionTemplates.removeFromOutput,
  "PrepEffect": functionTemplates.removeFromOutput,
  "RefreshEffect": functionTemplates.removeFromOutput,
  "SkinArray": functionTemplates.removeFromOutput,
  "SpawnEffect": functionTemplates.removeFromOutput,
  "SmartValidatorArray": functionTemplates.removeFromOutput,
  "TeleportEffect": functionTemplates.removeFromOutput,
  "Tooltip": functionTemplates.renderTooltip(),
  "TooltipAddendum": functionTemplates.renderTooltip(),
  "TooltipAppender": functionTemplates.valueFromAttributeIfOnlyHasKeys("button"),
  "TooltipCooldownOverrideText": functionTemplates.renderTooltip(),
  "UnloadCargoEffect": functionTemplates.removeFromOutput,
  "Validator": functionTemplates.removeFromOutput,
  "ValidatorArray": functionTemplates.removeFromOutput,
  "VariationArray": functionTemplates.removeFromOutput,
  "VOArray": functionTemplates.removeFromOutput,
  "VoiceLineArray": functionTemplates.removeFromOutput,
  "Weapon": functionTemplates.removeFromOutput,
  "WeaponArray": functionTemplates.removeFromOutput,
  "WhichEffect": functionTemplates.removeFromOutput,
}
